FROM ruby:3.2.3-slim

# Install essential build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /bolt

# Copy the Bolt source code
COPY . .

# Install dependencies without test group
RUN bundle install --path .bundle --without test